"use client";
import { INDICATORS, INDICATOR_IDS, NEAREST_WINDOW_YEARS } from "@/lib/worldbank/indicators";
import { Modal } from "./ui";

export function HowItWorks({ open, onClose }: { open: boolean; onClose: () => void }) {
  return (
    <Modal open={open} onClose={onClose} title="How the game works">
      <p><b className="text-brass">The board.</b> Every country in the World Bank country API is on the map. Pick any nation with enough data for a 20-year game. Your region is your board: rivals are the other countries in it, shown with their real World Bank data for each year. When your simulated development index passes a rival&apos;s, their territory falls under your development influence. Lead at least half your region to earn extra political capital every turn. You win by saving lives and raising living standards, never by conquest.</p>
      <p><b className="text-brass">Each turn</b> has four steps: <i>Intel</i> (world and domestic briefing), <i>Deploy</i> (commit one policy), <i>Resolve</i> (immediate and delayed effects) and <i>Fortune</i> (two seeded dice and a world event). The dice total scales the event from 0.7× to 1.3× strength.</p>
      <p><b className="text-sim">A story in ten chapters.</b> Each turn ends with a chapter: what happened in your simulated country because of your decision, the world event and dice, and a fictional political development. Then comes <i>what actually happened</i> in the real country over the same two years, told only from World Bank data. Real history is revealed one turn at a time, never ahead of the year you have reached.</p>
      <p><b className="text-mech">Fictional politics.</b> Elections every four years, protests, strikes, coalition demands and scandals are invented for the game. They respond to your public satisfaction, jobs and treasury, and change your political capital. They are not real events.</p>
      <p><b className="text-brass">Options that fit your country.</b> Every national problem has a pool of possible responses. Your ministries propose the four most relevant to your country, based on its data (for example farming share, electricity access, income level and emissions), and each card says why.</p>
      <p><b className="text-good">Impact ledger.</b> Indicators become people: infant lives saved (infant mortality × births), people gaining electricity (access × population), and extra CO2 emitted. During play you are compared with staying the course; at the end, with real history. These are simulated estimates.</p>
      <h3 className="pt-2 font-display text-lg uppercase tracking-wide">The simulation</h3>
      <p><b className="text-hist">Historical values</b> come from the World Bank Indicators API (v2, JSON, no key). They set your starting conditions, the pre-start trends your economy follows by default, the world conditions each turn, and the final comparison.</p>
      <p><b className="text-sim">Simulated values</b> are generated by the game&apos;s deterministic model. They are never World Bank observations, and the World Bank does not endorse them.</p>
      <p><b>Each turn</b>: new value = previous simulated value + the country&apos;s trend before the game started + your policy&apos;s effects + delayed effects of earlier policies + the world event + interactions (for example, trade exposure amplifies global slowdowns). Changes are clamped to stay plausible.</p>
      <p><b>No peeking</b>: during play the game only receives your country&apos;s data up to the start year. World conditions use global aggregates, which never include your country&apos;s own future. Your country&apos;s real path is fetched only for the final reveal.</p>
      <p><b>World events</b> are drawn with a seeded random generator. Their chances depend on real world data (a drop in world GDP growth makes a slowdown likely) and on your country&apos;s structure (trade, foreign investment and farming shares). Same seed and same decisions produce the same events.</p>
      <p><b>Missing data</b>: an exact-year observation is used when available, otherwise the nearest real observation within {NEAREST_WINDOW_YEARS} years (marked as nearest-year). Otherwise the indicator is left out. Missing data is never treated as zero.</p>
      <p><b>Scores</b>: each indicator scores 50 + 50 × tanh(change ÷ scale), so 50 means no change. Categories average their indicators. Your objective weights the categories. History is scored with the same formula from the same start, using only indicators that have a real end-year observation.</p>
      <p><b>Game mechanics</b>: treasury, political capital and public satisfaction are game rules, not data. They limit how much you can do at once.</p>
      <p className="text-muted">Associations and historical trends do not establish causation. Policy effects are simplified game rules chosen to be plausible and explainable.</p>
      <div className="mt-2 max-h-60 overflow-y-auto rounded-md border border-line">
        <table className="w-full text-left text-xs">
          <thead className="bg-panel-2 text-muted"><tr><th className="p-2">Indicator</th><th className="p-2">World Bank code</th></tr></thead>
          <tbody>{INDICATOR_IDS.map((id) => <tr key={id} className="border-t border-line"><td className="p-2">{INDICATORS[id].name}</td><td className="p-2 font-mono">{id === "education" ? "first available of SE.PRM.ENRR, SE.PRM.NENR, SE.SEC.ENRR, SE.TER.ENRR" : INDICATORS[id].code}</td></tr>)}</tbody>
        </table>
      </div>
      <p><a className="text-brass underline" href="/data" target="_blank">Open the data source page</a> to run a live World Bank API request.</p>
    </Modal>
  );
}
